# Generated by Django 5.2.5 on 2025-08-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techproducts',
            name='image_url',
        ),
        migrations.AddField(
            model_name='techproducts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='techproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='techproducts',
            name='instock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='techproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, null=True),
        ),
    ]
