# Generated by Django 5.2.5 on 2025-08-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_remove_techproducts_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techproducts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.techcategories'),
        ),
    ]
